Repository Netcracker/qubership-integration-ui, pull requests merged in 2025-07, with the labels that each got.

#64 feat: #16 Action Log page implementation
  eslint.config.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.ts
  src/api/apiTypes.ts
  src/api/rest/restApi.ts
  src/components/EnumColumnFilterDropdown.tsx
  src/components/ResizableTitle.tsx
  src/components/admin_tools/ActionsLog.tsx
  src/components/admin_tools/variables/VariablesTable.tsx
  src/components/modal/DateRangePicker.tsx
  src/components/modal/ImportChains.tsx
  src/components/sessions/SessionElementBodyView.tsx
  src/hooks/useActionLog.tsx
  src/hooks/useResizeHeigth.tsx
  src/misc/log-export-utils.ts
Labels: enhancement

#74 fix: fixed NotificationLogProvider callbacks
  src/components/notifications/contexts/NotificationLogContext.tsx
Labels: bug

#75 fix: Use chain list API to pass filters
  src/api/apiTypes.ts
  src/components/table/filter/Filter.tsx
  src/components/table/filter/FilterItem.tsx
  src/components/table/filter/filter.ts
  src/components/table/filter/value/StringFilterValue.tsx
  src/pages/Chains.tsx
Labels: bug

#65 feat: Date filter
  src/components/table/TimestampColumnFilterDropdown.tsx
  src/components/table/filter/Filter.tsx
  src/components/table/filter/FilterItem.tsx
  src/components/table/filter/filter.ts
  src/components/table/filter/value/StringFilterValue.tsx
  src/components/table/filter/value/TimestampFilterValue.tsx
  src/misc/date-utils.ts
Labels: enhancement

#82 feat: added implementation services build (#81)
  package-lock.json
  package.json
  src/api/api.ts
  src/api/apiTypes.ts
  src/api/rest/restApi.ts
  src/components/services/ImportSpecificationsModal.tsx
  src/components/services/ServiceApiSpecsTab.tsx
  src/components/services/Services.module.css
  src/components/services/ServicesTreeTable.tsx
Labels: enhancement

#83 feat: implemented generation of DDS
  eslint.config.js
  jest.config.ts
  package-lock.json
  package.json
  src/api/api.ts
  src/api/apiTypes.ts
  src/api/rest/restApi.ts
  src/components/modal/DdsPreview.module.css
  src/components/modal/DdsPreview.tsx
  src/components/modal/GenerateDdsModal.tsx
  src/components/modal/SequenceDiagram.module.css
  src/components/modal/SequenceDiagram.tsx
  src/components/modal/SnapshotSequenceDiagram.tsx
  src/components/services/ServicesTreeTable.tsx
  src/index.css
  src/mapper/markdown/markdown.ts
  src/mapper/model/generators.spec.ts
  src/mapper/model/generators.ts
  src/mapper/model/metadata.ts
  src/mapper/model/model.ts
  src/mapper/model/transformations.spec.ts
  src/mapper/model/transformations.ts
  src/mapper/util/actions.ts
  src/mapper/util/attributes.spec.ts
  src/mapper/util/attributes.ts
  src/mapper/util/mapping.spec.ts
  src/mapper/util/mapping.ts
  src/mapper/util/metadata.spec.ts
  src/mapper/util/metadata.ts
  src/mapper/util/schema.spec.ts
  src/mapper/util/schema.ts
  src/mapper/util/types.spec.ts
  src/mapper/util/types.ts
  src/pages/ChainGraph.tsx
  src/pages/Chains.tsx
  src/pages/Snapshots.tsx
  tsconfig.json
Labels: bug, enhancement

#84 feat: #70 Container Elements Implementation
  src/api/api.ts
  src/api/apiTypes.ts
  src/api/rest/restApi.ts
  src/components/LibraryContext.tsx
  src/components/elements_library/DraggableElement.tsx
  src/components/elements_library/ElementsLibrarySidebar.tsx
  src/components/graph/nodes/ChainGraphNodeTypes.ts
  src/components/graph/nodes/ContainerNode.tsx
  src/components/graph/nodes/UnitNode.tsx
  src/components/modal/ChainElementModification.tsx
  src/hooks/graph/useAutoLayout.tsx
  src/hooks/graph/useChainGraph.tsx
  src/hooks/useLibraryElement.tsx
  src/misc/chain-graph-utils.ts
  src/pages/ChainGraph.tsx
Labels: enhancement
