Repository Netcracker/qubership-integration-ui, pull requests merged in 2025-06, with the labels that each got.

#41 feat: implemented adding of variables to export archive of chains
  package-lock.json
  package.json
  src/api/admin-tools/variables/commonVariablesApi.ts
  src/api/admin-tools/variables/securedVariablesAPI.ts
  src/api/admin-tools/variables/types.ts
  src/api/admin-tools/variables/variablesApi.ts
  src/components/admin_tools/variables/CommonVariables.tsx
  src/components/admin_tools/variables/SecuredVariables.tsx
  src/pages/Chains.tsx
Labels: enhancement

#42 fix: #40 Improve performance of chain deployment statuses
  package-lock.json
  package.json
  src/api/rest/restApi.ts
  src/hooks/useDeployments.tsx
  src/misc/deployment-utils.ts
  src/pages/Deployments.tsx
Labels: bug

#44 fix: fixed placement of tooltips on floating buttons
  src/pages/Chains.tsx
  src/pages/Deployments.tsx
  src/pages/LoggingSettings.tsx
  src/pages/SessionPage.tsx
  src/pages/Sessions.tsx
  src/pages/Snapshots.tsx
Labels: bug

#48 fix: aligned repository with requirements
  .github/CODEOWNERS
  .github/super-linter.env
  CODE-OF-CONDUCT.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: bug

#49 fix/fix-variables-api
  src/api/admin-tools/variables/baseApi.ts
  src/api/admin-tools/variables/commonVariablesApi.ts
  src/api/admin-tools/variables/securedVariablesAPI.ts
  src/api/admin-tools/variables/types.ts
  src/components/admin_tools/variables/ImportVariablesModal.tsx
  src/components/admin_tools/variables/SecuredVariables.tsx
Labels: bug

#52 feat: Domains page implementation
  package-lock.json
  src/App.tsx
  src/api/api.ts
  src/api/apiTypes.ts
  src/api/rest/restApi.ts
  src/components/admin_tools/CommonStyle.module.css
  src/components/admin_tools/domains/DeploymentsTable.tsx
  src/components/admin_tools/domains/Domains.tsx
  src/components/admin_tools/domains/DomainsTable.tsx
  src/components/admin_tools/domains/EngineTable.tsx
  src/components/admin_tools/domains/Tables.module.css
  src/components/admin_tools/domains/hooks/useDeploymentsForEngine.ts
  src/components/admin_tools/domains/hooks/useEngines.ts
  src/components/admin_tools/domains/hooks/useError.ts
  src/components/admin_tools/variables/CommonVariables.tsx
  src/components/admin_tools/variables/SecuredVariables.module.css
  src/components/admin_tools/variables/SecuredVariables.tsx
  src/components/admin_tools/variables/VariablesTable.module.css
  src/components/admin_tools/variables/VariablesTable.tsx
  src/components/admin_tools/variables/variables.module.css
  src/components/graph/CustomControls.module.css
  src/components/notifications/EventPooling.tsx
  src/hooks/useDeployments.tsx
  src/hooks/useDomains.tsx
  src/pages/admin-tools/AdminToolsPage.module.css
  src/pages/admin-tools/CommonVariablesPage.tsx
  src/pages/admin-tools/DomainsPage.tsx
  src/pages/admin-tools/SecuredVariablesPage.tsx
Labels: bug, enhancement

#69 feat: added redirect from engine-list to domains
  src/App.tsx
Labels: enhancement
